### ISSUE TITLE
Comment: Simple Mobile Tools - Problematic new owner

### ISSUE THREAD

**Issue by lintux** [stephanritscher/Simple-Contacts#16]
Hi @stephanritscher ,

looking at the [latest development](https://github.com/SimpleMobileTools/General-Discussion/issues/241) it seems like staying disconnected from the original SMT project or joing here https://github.com/FossifyOrg  might be a good move?

BR
Stephan (really enjoing this version of Simple contacts)

**Comment by stephanritscher** [comment]
Hi #lintux,

interesting news - thanks for the hint. Sounds like the now fork could solve the blocking of some contributions like mine.

Best regards,
Stephan

05.12.2023 12:07:09 lintux ***@***.***>:

**Comment by lintux** [comment]
> @lintux @stephanritscher the fork was renamed, please update the link to https://github.com/FossifyOrg

Done

**Comment by Cwpute** [comment]
Maybe we should consider renaming this app to distance it from Simple Mobile Tools ? Since they will seemingly continue to operate under this name, but as a for profit with a possible trademark on the name, it would help avoid any future legal issue…

**Comment by Cwpute** [comment]
FossifyOrg has released their first version of the SMT fork, including some new updates, and i haven't seen any special communication between your two projects.

So what's the plan ?
Should we continue using your fork for your own contributions ? will we see them contributed to the Fossify fork ?

**Comment by stephanritscher** [comment]
I still have the plan to contribute. I just rebased to the latest upstream version by Tibbi as a preparation. I will see when I can find some more time for the next step.

**Comment by lintux** [comment]
Hi @stephanritscher ,

as just saw an update of the Fossify Version of contact ... And news in the above discussed approach?

BR
lintux

**Comment by stephanritscher** [comment]
There is very recent progress on https://github.com/FossifyOrg/Contacts/pull/57.
